name: Deploy static site to Netlify

on:
  push:
    branches: ["main"]   # Deploy when pushing to main
  workflow_dispatch:      # Allow manual trigger from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🚀 Deploy directly (no build step needed)
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: .     
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GitHub Action deploy"
          enable-pull-request-comment: false
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

